// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tTest_tCalc2 (
        tCalc1ResultA,
        tCalc1ResultB,
        p_read,
        t,
        ap_clk,
        ap_rst,
        tCalc1ResultB_ap_vld,
        tCalc1ResultA_ap_vld,
        p_read_ap_vld,
        t_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] tCalc1ResultA;
input  [31:0] tCalc1ResultB;
input  [15:0] p_read;
output  [31:0] t;
input   ap_clk;
input   ap_rst;
input   tCalc1ResultB_ap_vld;
input   tCalc1ResultA_ap_vld;
input   p_read_ap_vld;
output   t_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    tCalc2_Block_entry12_proc_U0_ap_start;
wire    tCalc2_Block_entry12_proc_U0_ap_done;
wire    tCalc2_Block_entry12_proc_U0_ap_continue;
wire    tCalc2_Block_entry12_proc_U0_ap_idle;
wire    tCalc2_Block_entry12_proc_U0_ap_ready;
wire   [31:0] tCalc2_Block_entry12_proc_U0_t;

tTest_tCalc2_Block_entry12_proc tCalc2_Block_entry12_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(tCalc2_Block_entry12_proc_U0_ap_start),
    .ap_done(tCalc2_Block_entry12_proc_U0_ap_done),
    .ap_continue(tCalc2_Block_entry12_proc_U0_ap_continue),
    .ap_idle(tCalc2_Block_entry12_proc_U0_ap_idle),
    .ap_ready(tCalc2_Block_entry12_proc_U0_ap_ready),
    .tCalc1ResultB(tCalc1ResultB),
    .tCalc1ResultA(tCalc1ResultA),
    .p_read(p_read),
    .t(tCalc2_Block_entry12_proc_U0_t)
);

assign ap_done = tCalc2_Block_entry12_proc_U0_ap_done;

assign ap_idle = tCalc2_Block_entry12_proc_U0_ap_idle;

assign ap_ready = tCalc2_Block_entry12_proc_U0_ap_ready;

assign t = tCalc2_Block_entry12_proc_U0_t;

assign tCalc2_Block_entry12_proc_U0_ap_continue = ap_continue;

assign tCalc2_Block_entry12_proc_U0_ap_start = ap_start;

assign t_ap_vld = 1'b1;

endmodule //tTest_tCalc2
