// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tTest_Block_entry2347_proc6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        C_dout,
        C_num_data_valid,
        C_fifo_cap,
        C_empty_n,
        C_read,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        p_read2,
        p_read3,
        famA_address0,
        famA_ce0,
        famA_q0,
        famB_address0,
        famB_ce0,
        famB_q0
);

parameter    ap_ST_fsm_state1 = 88'd1;
parameter    ap_ST_fsm_state2 = 88'd2;
parameter    ap_ST_fsm_state3 = 88'd4;
parameter    ap_ST_fsm_state4 = 88'd8;
parameter    ap_ST_fsm_state5 = 88'd16;
parameter    ap_ST_fsm_state6 = 88'd32;
parameter    ap_ST_fsm_state7 = 88'd64;
parameter    ap_ST_fsm_state8 = 88'd128;
parameter    ap_ST_fsm_state9 = 88'd256;
parameter    ap_ST_fsm_state10 = 88'd512;
parameter    ap_ST_fsm_state11 = 88'd1024;
parameter    ap_ST_fsm_state12 = 88'd2048;
parameter    ap_ST_fsm_state13 = 88'd4096;
parameter    ap_ST_fsm_state14 = 88'd8192;
parameter    ap_ST_fsm_state15 = 88'd16384;
parameter    ap_ST_fsm_state16 = 88'd32768;
parameter    ap_ST_fsm_state17 = 88'd65536;
parameter    ap_ST_fsm_state18 = 88'd131072;
parameter    ap_ST_fsm_state19 = 88'd262144;
parameter    ap_ST_fsm_state20 = 88'd524288;
parameter    ap_ST_fsm_state21 = 88'd1048576;
parameter    ap_ST_fsm_state22 = 88'd2097152;
parameter    ap_ST_fsm_state23 = 88'd4194304;
parameter    ap_ST_fsm_state24 = 88'd8388608;
parameter    ap_ST_fsm_state25 = 88'd16777216;
parameter    ap_ST_fsm_state26 = 88'd33554432;
parameter    ap_ST_fsm_state27 = 88'd67108864;
parameter    ap_ST_fsm_state28 = 88'd134217728;
parameter    ap_ST_fsm_state29 = 88'd268435456;
parameter    ap_ST_fsm_state30 = 88'd536870912;
parameter    ap_ST_fsm_state31 = 88'd1073741824;
parameter    ap_ST_fsm_state32 = 88'd2147483648;
parameter    ap_ST_fsm_state33 = 88'd4294967296;
parameter    ap_ST_fsm_state34 = 88'd8589934592;
parameter    ap_ST_fsm_state35 = 88'd17179869184;
parameter    ap_ST_fsm_state36 = 88'd34359738368;
parameter    ap_ST_fsm_state37 = 88'd68719476736;
parameter    ap_ST_fsm_state38 = 88'd137438953472;
parameter    ap_ST_fsm_state39 = 88'd274877906944;
parameter    ap_ST_fsm_state40 = 88'd549755813888;
parameter    ap_ST_fsm_state41 = 88'd1099511627776;
parameter    ap_ST_fsm_state42 = 88'd2199023255552;
parameter    ap_ST_fsm_state43 = 88'd4398046511104;
parameter    ap_ST_fsm_state44 = 88'd8796093022208;
parameter    ap_ST_fsm_state45 = 88'd17592186044416;
parameter    ap_ST_fsm_state46 = 88'd35184372088832;
parameter    ap_ST_fsm_state47 = 88'd70368744177664;
parameter    ap_ST_fsm_state48 = 88'd140737488355328;
parameter    ap_ST_fsm_state49 = 88'd281474976710656;
parameter    ap_ST_fsm_state50 = 88'd562949953421312;
parameter    ap_ST_fsm_state51 = 88'd1125899906842624;
parameter    ap_ST_fsm_state52 = 88'd2251799813685248;
parameter    ap_ST_fsm_state53 = 88'd4503599627370496;
parameter    ap_ST_fsm_state54 = 88'd9007199254740992;
parameter    ap_ST_fsm_state55 = 88'd18014398509481984;
parameter    ap_ST_fsm_state56 = 88'd36028797018963968;
parameter    ap_ST_fsm_state57 = 88'd72057594037927936;
parameter    ap_ST_fsm_state58 = 88'd144115188075855872;
parameter    ap_ST_fsm_state59 = 88'd288230376151711744;
parameter    ap_ST_fsm_state60 = 88'd576460752303423488;
parameter    ap_ST_fsm_state61 = 88'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 88'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 88'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 88'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 88'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 88'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 88'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 88'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 88'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 88'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 88'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 88'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 88'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 88'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 88'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 88'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 88'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 88'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 88'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 88'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 88'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 88'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 88'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 88'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 88'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 88'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 88'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 88'd154742504910672534362390528;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [39:0] p_read;
input  [39:0] p_read1;
input  [31:0] C_dout;
input  [2:0] C_num_data_valid;
input  [2:0] C_fifo_cap;
input   C_empty_n;
output   C_read;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [31:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [31:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [1:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [46:0] p_read2;
input  [46:0] p_read3;
output  [7:0] famA_address0;
output   famA_ce0;
input  [31:0] famA_q0;
output  [7:0] famB_address0;
output   famB_ce0;
input  [31:0] famB_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg C_read;
reg m_axi_gmem_AWVALID;
reg m_axi_gmem_WVALID;
reg m_axi_gmem_BREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [87:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    C_blk_n;
wire    ap_CS_fsm_state2;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state82;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state83;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state88;
reg    ap_block_state1;
reg   [31:0] C_read_reg_368;
wire   [0:0] or_ln82_fu_196_p2;
reg   [0:0] or_ln82_reg_373;
wire   [31:0] grp_fu_212_p2;
reg   [31:0] udiv_ln23_reg_397;
wire    ap_CS_fsm_state76;
wire   [31:0] grp_fu_228_p2;
reg   [31:0] udiv_ln23_1_reg_402;
wire   [31:0] meanA_fu_239_p1;
reg   [31:0] meanA_reg_407;
wire    ap_CS_fsm_state77;
wire   [31:0] meanB_fu_243_p1;
reg   [31:0] meanB_reg_412;
wire   [31:0] meanDiff_fu_265_p3;
reg   [31:0] meanDiff_reg_417;
wire    grp_tCalc2_fu_178_ap_done;
wire    grp_tCalc2_fu_178_ap_ready;
wire    ap_sync_grp_tCalc2_fu_178_ap_ready;
wire    ap_sync_grp_tCalc2_fu_178_ap_done;
reg    ap_block_state82_on_subcall_done;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_done;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_idle;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_ready;
wire   [7:0] grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_famA_address0;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_famA_ce0;
wire   [62:0] grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_tmpSum_out;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_tmpSum_out_ap_vld;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_done;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_idle;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_ready;
wire   [7:0] grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_famB_address0;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_famB_ce0;
wire   [62:0] grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_tmpSum_2_out;
wire    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_tmpSum_2_out_ap_vld;
wire   [63:0] grp_tCalc1_fu_164_out_r;
wire    grp_tCalc1_fu_164_out_r_ap_vld;
wire    grp_tCalc1_fu_164_ap_start;
wire    grp_tCalc1_fu_164_ap_done;
wire    grp_tCalc1_fu_164_ap_ready;
wire    grp_tCalc1_fu_164_ap_idle;
reg    grp_tCalc1_fu_164_ap_continue;
wire   [63:0] grp_tCalc1_fu_171_out_r;
wire    grp_tCalc1_fu_171_out_r_ap_vld;
wire    grp_tCalc1_fu_171_ap_start;
wire    grp_tCalc1_fu_171_ap_done;
wire    grp_tCalc1_fu_171_ap_ready;
wire    grp_tCalc1_fu_171_ap_idle;
reg    grp_tCalc1_fu_171_ap_continue;
wire   [31:0] grp_tCalc2_fu_178_t;
wire    grp_tCalc2_fu_178_t_ap_vld;
wire    grp_tCalc2_fu_178_ap_start;
wire    grp_tCalc2_fu_178_ap_idle;
reg    grp_tCalc2_fu_178_ap_continue;
reg    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start_reg;
wire    ap_CS_fsm_state78;
reg    grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start_reg;
reg    grp_tCalc1_fu_164_ap_start_reg;
wire    ap_CS_fsm_state79;
wire    ap_CS_fsm_state80;
wire    ap_sync_grp_tCalc1_fu_164_ap_ready;
wire    ap_sync_grp_tCalc1_fu_164_ap_done;
wire    ap_sync_grp_tCalc1_fu_171_ap_ready;
wire    ap_sync_grp_tCalc1_fu_171_ap_done;
reg    ap_block_state80_on_subcall_done;
reg    ap_sync_reg_grp_tCalc1_fu_164_ap_ready;
reg    ap_sync_reg_grp_tCalc1_fu_164_ap_done;
reg   [63:0] tCalc1ResultA_fu_94;
reg    grp_tCalc1_fu_171_ap_start_reg;
reg    ap_sync_reg_grp_tCalc1_fu_171_ap_ready;
reg    ap_sync_reg_grp_tCalc1_fu_171_ap_done;
reg   [63:0] tCalc1ResultB_fu_98;
reg    grp_tCalc2_fu_178_ap_start_reg;
wire    ap_CS_fsm_state81;
reg    ap_sync_reg_grp_tCalc2_fu_178_ap_ready;
reg    ap_sync_reg_grp_tCalc2_fu_178_ap_done;
reg   [31:0] t_fu_90;
wire  signed [31:0] sext_ln94_fu_298_p1;
wire   [0:0] icmp_ln82_fu_186_p2;
wire   [0:0] icmp_ln82_1_fu_191_p2;
wire   [70:0] grp_fu_212_p0;
wire   [39:0] grp_fu_212_p1;
wire   [70:0] grp_fu_228_p0;
wire   [39:0] grp_fu_228_p1;
wire   [0:0] icmp_ln27_fu_247_p2;
wire   [31:0] sub_ln27_fu_253_p2;
wire   [31:0] sub_ln27_1_fu_259_p2;
wire   [29:0] trunc_ln2_fu_289_p4;
reg    grp_fu_212_ap_start;
wire    grp_fu_212_ap_done;
reg    grp_fu_212_ce;
wire    ap_CS_fsm_state84;
wire    ap_CS_fsm_state85;
wire    ap_CS_fsm_state86;
wire    ap_CS_fsm_state87;
reg    grp_fu_228_ap_start;
wire    grp_fu_228_ap_done;
reg    grp_fu_228_ce;
reg   [87:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
reg    ap_block_state78_on_subcall_done;
reg    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
reg    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
reg    ap_ST_fsm_state82_blk;
reg    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
reg    ap_ST_fsm_state88_blk;
wire   [70:0] grp_fu_212_p10;
wire   [70:0] grp_fu_228_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 88'd1;
#0 C_read_reg_368 = 32'd0;
#0 or_ln82_reg_373 = 1'd0;
#0 udiv_ln23_reg_397 = 32'd0;
#0 udiv_ln23_1_reg_402 = 32'd0;
#0 meanA_reg_407 = 32'd0;
#0 meanB_reg_412 = 32'd0;
#0 meanDiff_reg_417 = 32'd0;
#0 grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start_reg = 1'b0;
#0 grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start_reg = 1'b0;
#0 grp_tCalc1_fu_164_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_tCalc1_fu_164_ap_ready = 1'b0;
#0 ap_sync_reg_grp_tCalc1_fu_164_ap_done = 1'b0;
#0 tCalc1ResultA_fu_94 = 64'd0;
#0 grp_tCalc1_fu_171_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_tCalc1_fu_171_ap_ready = 1'b0;
#0 ap_sync_reg_grp_tCalc1_fu_171_ap_done = 1'b0;
#0 tCalc1ResultB_fu_98 = 64'd0;
#0 grp_tCalc2_fu_178_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_tCalc2_fu_178_ap_ready = 1'b0;
#0 ap_sync_reg_grp_tCalc2_fu_178_ap_done = 1'b0;
#0 t_fu_90 = 32'd0;
end

tTest_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1 grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start),
    .ap_done(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_done),
    .ap_idle(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_idle),
    .ap_ready(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_ready),
    .zext_ln35(meanA_reg_407),
    .famA_address0(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_famA_address0),
    .famA_ce0(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_famA_ce0),
    .famA_q0(famA_q0),
    .tmpSum_out(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_tmpSum_out),
    .tmpSum_out_ap_vld(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_tmpSum_out_ap_vld)
);

tTest_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11 grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start),
    .ap_done(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_done),
    .ap_idle(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_idle),
    .ap_ready(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_ready),
    .zext_ln35_1(meanB_reg_412),
    .famB_address0(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_famB_address0),
    .famB_ce0(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_famB_ce0),
    .famB_q0(famB_q0),
    .tmpSum_2_out(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_tmpSum_2_out),
    .tmpSum_2_out_ap_vld(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_tmpSum_2_out_ap_vld)
);

tTest_tCalc1 grp_tCalc1_fu_164(
    .varSum(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_tmpSum_out),
    .numData(p_read),
    .out_r(grp_tCalc1_fu_164_out_r),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .numData_ap_vld(1'b1),
    .varSum_ap_vld(1'b1),
    .out_r_ap_vld(grp_tCalc1_fu_164_out_r_ap_vld),
    .ap_start(grp_tCalc1_fu_164_ap_start),
    .ap_done(grp_tCalc1_fu_164_ap_done),
    .ap_ready(grp_tCalc1_fu_164_ap_ready),
    .ap_idle(grp_tCalc1_fu_164_ap_idle),
    .ap_continue(grp_tCalc1_fu_164_ap_continue)
);

tTest_tCalc1 grp_tCalc1_fu_171(
    .varSum(grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_tmpSum_2_out),
    .numData(p_read1),
    .out_r(grp_tCalc1_fu_171_out_r),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .numData_ap_vld(1'b1),
    .varSum_ap_vld(1'b1),
    .out_r_ap_vld(grp_tCalc1_fu_171_out_r_ap_vld),
    .ap_start(grp_tCalc1_fu_171_ap_start),
    .ap_done(grp_tCalc1_fu_171_ap_done),
    .ap_ready(grp_tCalc1_fu_171_ap_ready),
    .ap_idle(grp_tCalc1_fu_171_ap_idle),
    .ap_continue(grp_tCalc1_fu_171_ap_continue)
);

tTest_tCalc2 grp_tCalc2_fu_178(
    .tCalc1ResultA(tCalc1ResultA_fu_94),
    .tCalc1ResultB(tCalc1ResultB_fu_98),
    .meanDiff(meanDiff_reg_417),
    .t(grp_tCalc2_fu_178_t),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .tCalc1ResultB_ap_vld(1'b1),
    .tCalc1ResultA_ap_vld(1'b1),
    .meanDiff_ap_vld(1'b1),
    .t_ap_vld(grp_tCalc2_fu_178_t_ap_vld),
    .ap_start(grp_tCalc2_fu_178_ap_start),
    .ap_done(grp_tCalc2_fu_178_ap_done),
    .ap_ready(grp_tCalc2_fu_178_ap_ready),
    .ap_idle(grp_tCalc2_fu_178_ap_idle),
    .ap_continue(grp_tCalc2_fu_178_ap_continue)
);

tTest_udiv_71ns_40ns_32_75_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 75 ),
    .din0_WIDTH( 71 ),
    .din1_WIDTH( 40 ),
    .dout_WIDTH( 32 ))
udiv_71ns_40ns_32_75_seq_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_212_ap_start),
    .done(grp_fu_212_ap_done),
    .din0(grp_fu_212_p0),
    .din1(grp_fu_212_p1),
    .ce(grp_fu_212_ce),
    .dout(grp_fu_212_p2)
);

tTest_udiv_71ns_40ns_32_75_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 75 ),
    .din0_WIDTH( 71 ),
    .din1_WIDTH( 40 ),
    .dout_WIDTH( 32 ))
udiv_71ns_40ns_32_75_seq_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_228_ap_start),
    .done(grp_fu_228_ap_done),
    .din0(grp_fu_228_p0),
    .din1(grp_fu_228_p1),
    .ce(grp_fu_228_ce),
    .dout(grp_fu_228_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        C_read_reg_368 <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == C_empty_n))) begin
            C_read_reg_368 <= C_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state88) & (m_axi_gmem_BVALID == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_tCalc1_fu_164_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state80_on_subcall_done) & (1'b1 == ap_CS_fsm_state80))) begin
            ap_sync_reg_grp_tCalc1_fu_164_ap_done <= 1'b0;
        end else if ((grp_tCalc1_fu_164_ap_done == 1'b1)) begin
            ap_sync_reg_grp_tCalc1_fu_164_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_tCalc1_fu_164_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state80_on_subcall_done) & (1'b1 == ap_CS_fsm_state80))) begin
            ap_sync_reg_grp_tCalc1_fu_164_ap_ready <= 1'b0;
        end else if ((grp_tCalc1_fu_164_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_tCalc1_fu_164_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_tCalc1_fu_171_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state80_on_subcall_done) & (1'b1 == ap_CS_fsm_state80))) begin
            ap_sync_reg_grp_tCalc1_fu_171_ap_done <= 1'b0;
        end else if ((grp_tCalc1_fu_171_ap_done == 1'b1)) begin
            ap_sync_reg_grp_tCalc1_fu_171_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_tCalc1_fu_171_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state80_on_subcall_done) & (1'b1 == ap_CS_fsm_state80))) begin
            ap_sync_reg_grp_tCalc1_fu_171_ap_ready <= 1'b0;
        end else if ((grp_tCalc1_fu_171_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_tCalc1_fu_171_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_tCalc2_fu_178_ap_done <= 1'b0;
    end else begin
        if ((~((m_axi_gmem_AWREADY == 1'b0) | (1'b1 == ap_block_state82_on_subcall_done)) & (or_ln82_reg_373 == 1'd0) & (1'b1 == ap_CS_fsm_state82))) begin
            ap_sync_reg_grp_tCalc2_fu_178_ap_done <= 1'b0;
        end else if ((grp_tCalc2_fu_178_ap_done == 1'b1)) begin
            ap_sync_reg_grp_tCalc2_fu_178_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_tCalc2_fu_178_ap_ready <= 1'b0;
    end else begin
        if ((~((m_axi_gmem_AWREADY == 1'b0) | (1'b1 == ap_block_state82_on_subcall_done)) & (or_ln82_reg_373 == 1'd0) & (1'b1 == ap_CS_fsm_state82))) begin
            ap_sync_reg_grp_tCalc2_fu_178_ap_ready <= 1'b0;
        end else if ((grp_tCalc2_fu_178_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_tCalc2_fu_178_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state77)) begin
            grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_ready == 1'b1)) begin
            grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state77)) begin
            grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_ready == 1'b1)) begin
            grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tCalc1_fu_164_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state79) | ((ap_sync_grp_tCalc1_fu_164_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state80)))) begin
            grp_tCalc1_fu_164_ap_start_reg <= 1'b1;
        end else if ((grp_tCalc1_fu_164_ap_ready == 1'b1)) begin
            grp_tCalc1_fu_164_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tCalc1_fu_171_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state79) | ((ap_sync_grp_tCalc1_fu_171_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state80)))) begin
            grp_tCalc1_fu_171_ap_start_reg <= 1'b1;
        end else if ((grp_tCalc1_fu_171_ap_ready == 1'b1)) begin
            grp_tCalc1_fu_171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tCalc2_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state81) | ((ap_sync_grp_tCalc2_fu_178_ap_ready == 1'b0) & (or_ln82_reg_373 == 1'd0) & (1'b1 == ap_CS_fsm_state82)))) begin
            grp_tCalc2_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_tCalc2_fu_178_ap_ready == 1'b1)) begin
            grp_tCalc2_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        meanA_reg_407 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state77)) begin
            meanA_reg_407 <= meanA_fu_239_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        meanB_reg_412 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state77)) begin
            meanB_reg_412 <= meanB_fu_243_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        meanDiff_reg_417 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state77)) begin
            meanDiff_reg_417 <= meanDiff_fu_265_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln82_reg_373 <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == C_empty_n))) begin
            or_ln82_reg_373 <= or_ln82_fu_196_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tCalc1ResultA_fu_94 <= 64'd0;
    end else begin
        if (((grp_tCalc1_fu_164_out_r_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state80))) begin
            tCalc1ResultA_fu_94 <= grp_tCalc1_fu_164_out_r;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tCalc1ResultB_fu_98 <= 64'd0;
    end else begin
        if (((grp_tCalc1_fu_171_out_r_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state80))) begin
            tCalc1ResultB_fu_98 <= grp_tCalc1_fu_171_out_r;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        t_fu_90 <= 32'd0;
    end else begin
        if (((or_ln82_fu_196_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b1 == C_empty_n))) begin
            t_fu_90 <= 32'd0;
        end else if (((grp_tCalc2_fu_178_t_ap_vld == 1'b1) & (or_ln82_reg_373 == 1'd0) & (1'b1 == ap_CS_fsm_state82))) begin
            t_fu_90 <= grp_tCalc2_fu_178_t;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        udiv_ln23_1_reg_402 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state76)) begin
            udiv_ln23_1_reg_402 <= grp_fu_228_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        udiv_ln23_reg_397 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state76)) begin
            udiv_ln23_reg_397 <= grp_fu_212_p2;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_blk_n = C_empty_n;
    end else begin
        C_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == C_empty_n))) begin
        C_read = 1'b1;
    end else begin
        C_read = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b0 == C_empty_n)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state78_on_subcall_done)) begin
        ap_ST_fsm_state78_blk = 1'b1;
    end else begin
        ap_ST_fsm_state78_blk = 1'b0;
    end
end

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state80_on_subcall_done)) begin
        ap_ST_fsm_state80_blk = 1'b1;
    end else begin
        ap_ST_fsm_state80_blk = 1'b0;
    end
end

assign ap_ST_fsm_state81_blk = 1'b0;

always @ (*) begin
    if (((m_axi_gmem_AWREADY == 1'b0) | (1'b1 == ap_block_state82_on_subcall_done))) begin
        ap_ST_fsm_state82_blk = 1'b1;
    end else begin
        ap_ST_fsm_state82_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_WREADY == 1'b0)) begin
        ap_ST_fsm_state83_blk = 1'b1;
    end else begin
        ap_ST_fsm_state83_blk = 1'b0;
    end
end

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state88_blk = 1'b1;
    end else begin
        ap_ST_fsm_state88_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state88) & (m_axi_gmem_BVALID == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state88) & (m_axi_gmem_BVALID == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state82)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state88)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state83)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((or_ln82_fu_196_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b1 == C_empty_n))) begin
        grp_fu_212_ap_start = 1'b1;
    end else begin
        grp_fu_212_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state86) | (1'b1 == ap_CS_fsm_state85) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state88) | (1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_212_ce = 1'b0;
    end else begin
        grp_fu_212_ce = 1'b1;
    end
end

always @ (*) begin
    if (((or_ln82_fu_196_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b1 == C_empty_n))) begin
        grp_fu_228_ap_start = 1'b1;
    end else begin
        grp_fu_228_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state86) | (1'b1 == ap_CS_fsm_state85) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state88) | (1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_228_ce = 1'b0;
    end else begin
        grp_fu_228_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state80_on_subcall_done) & (1'b1 == ap_CS_fsm_state80))) begin
        grp_tCalc1_fu_164_ap_continue = 1'b1;
    end else begin
        grp_tCalc1_fu_164_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state80_on_subcall_done) & (1'b1 == ap_CS_fsm_state80))) begin
        grp_tCalc1_fu_171_ap_continue = 1'b1;
    end else begin
        grp_tCalc1_fu_171_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_AWREADY == 1'b0) | (1'b1 == ap_block_state82_on_subcall_done)) & (or_ln82_reg_373 == 1'd0) & (1'b1 == ap_CS_fsm_state82))) begin
        grp_tCalc2_fu_178_ap_continue = 1'b1;
    end else begin
        grp_tCalc2_fu_178_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_AWREADY == 1'b0) | (1'b1 == ap_block_state82_on_subcall_done)) & (1'b1 == ap_CS_fsm_state82))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state88) & (m_axi_gmem_BVALID == 1'b1))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) & (m_axi_gmem_WREADY == 1'b1))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((or_ln82_fu_196_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b1 == C_empty_n))) begin
                ap_NS_fsm = ap_ST_fsm_state82;
            end else if (((or_ln82_fu_196_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b1 == C_empty_n))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            if (((1'b0 == ap_block_state78_on_subcall_done) & (1'b1 == ap_CS_fsm_state78))) begin
                ap_NS_fsm = ap_ST_fsm_state79;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            if (((1'b0 == ap_block_state80_on_subcall_done) & (1'b1 == ap_CS_fsm_state80))) begin
                ap_NS_fsm = ap_ST_fsm_state81;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state80;
            end
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            if ((~((m_axi_gmem_AWREADY == 1'b0) | (1'b1 == ap_block_state82_on_subcall_done)) & (1'b1 == ap_CS_fsm_state82))) begin
                ap_NS_fsm = ap_ST_fsm_state83;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state82;
            end
        end
        ap_ST_fsm_state83 : begin
            if (((1'b1 == ap_CS_fsm_state83) & (m_axi_gmem_WREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state84;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state83;
            end
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            if (((1'b1 == ap_CS_fsm_state88) & (m_axi_gmem_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state88;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state79 = ap_CS_fsm[32'd78];

assign ap_CS_fsm_state80 = ap_CS_fsm[32'd79];

assign ap_CS_fsm_state81 = ap_CS_fsm[32'd80];

assign ap_CS_fsm_state82 = ap_CS_fsm[32'd81];

assign ap_CS_fsm_state83 = ap_CS_fsm[32'd82];

assign ap_CS_fsm_state84 = ap_CS_fsm[32'd83];

assign ap_CS_fsm_state85 = ap_CS_fsm[32'd84];

assign ap_CS_fsm_state86 = ap_CS_fsm[32'd85];

assign ap_CS_fsm_state87 = ap_CS_fsm[32'd86];

assign ap_CS_fsm_state88 = ap_CS_fsm[32'd87];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state78_on_subcall_done = ((grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_done == 1'b0) | (grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state80_on_subcall_done = (((ap_sync_grp_tCalc1_fu_171_ap_ready & ap_sync_grp_tCalc1_fu_171_ap_done) == 1'b0) | ((ap_sync_grp_tCalc1_fu_164_ap_ready & ap_sync_grp_tCalc1_fu_164_ap_done) == 1'b0));
end

always @ (*) begin
    ap_block_state82_on_subcall_done = (((ap_sync_grp_tCalc2_fu_178_ap_ready & ap_sync_grp_tCalc2_fu_178_ap_done) == 1'b0) & (or_ln82_reg_373 == 1'd0));
end

assign ap_sync_grp_tCalc1_fu_164_ap_done = (grp_tCalc1_fu_164_ap_done | ap_sync_reg_grp_tCalc1_fu_164_ap_done);

assign ap_sync_grp_tCalc1_fu_164_ap_ready = (grp_tCalc1_fu_164_ap_ready | ap_sync_reg_grp_tCalc1_fu_164_ap_ready);

assign ap_sync_grp_tCalc1_fu_171_ap_done = (grp_tCalc1_fu_171_ap_done | ap_sync_reg_grp_tCalc1_fu_171_ap_done);

assign ap_sync_grp_tCalc1_fu_171_ap_ready = (grp_tCalc1_fu_171_ap_ready | ap_sync_reg_grp_tCalc1_fu_171_ap_ready);

assign ap_sync_grp_tCalc2_fu_178_ap_done = (grp_tCalc2_fu_178_ap_done | ap_sync_reg_grp_tCalc2_fu_178_ap_done);

assign ap_sync_grp_tCalc2_fu_178_ap_ready = (grp_tCalc2_fu_178_ap_ready | ap_sync_reg_grp_tCalc2_fu_178_ap_ready);

assign famA_address0 = grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_famA_address0;

assign famA_ce0 = grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_famA_ce0;

assign famB_address0 = grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_famB_address0;

assign famB_ce0 = grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_famB_ce0;

assign grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start = grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_11_fu_156_ap_start_reg;

assign grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start = grp_Block_entry2347_proc6_Pipeline_VITIS_LOOP_35_1_fu_148_ap_start_reg;

assign grp_fu_212_p0 = {{p_read2}, {24'd0}};

assign grp_fu_212_p1 = grp_fu_212_p10;

assign grp_fu_212_p10 = p_read;

assign grp_fu_228_p0 = {{p_read3}, {24'd0}};

assign grp_fu_228_p1 = grp_fu_228_p10;

assign grp_fu_228_p10 = p_read1;

assign grp_tCalc1_fu_164_ap_start = grp_tCalc1_fu_164_ap_start_reg;

assign grp_tCalc1_fu_171_ap_start = grp_tCalc1_fu_171_ap_start_reg;

assign grp_tCalc2_fu_178_ap_start = grp_tCalc2_fu_178_ap_start_reg;

assign icmp_ln27_fu_247_p2 = ((meanA_fu_239_p1 > meanB_fu_243_p1) ? 1'b1 : 1'b0);

assign icmp_ln82_1_fu_191_p2 = ((p_read1 == 40'd0) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_186_p2 = ((p_read == 40'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = 32'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = sext_ln94_fu_298_p1;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd1;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WDATA = t_fu_90;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd15;

assign m_axi_gmem_WUSER = 1'd0;

assign meanA_fu_239_p1 = udiv_ln23_reg_397[31:0];

assign meanB_fu_243_p1 = udiv_ln23_1_reg_402[31:0];

assign meanDiff_fu_265_p3 = ((icmp_ln27_fu_247_p2[0:0] == 1'b1) ? sub_ln27_fu_253_p2 : sub_ln27_1_fu_259_p2);

assign or_ln82_fu_196_p2 = (icmp_ln82_fu_186_p2 | icmp_ln82_1_fu_191_p2);

assign sext_ln94_fu_298_p1 = $signed(trunc_ln2_fu_289_p4);

assign sub_ln27_1_fu_259_p2 = (meanB_fu_243_p1 - meanA_fu_239_p1);

assign sub_ln27_fu_253_p2 = (meanA_fu_239_p1 - meanB_fu_243_p1);

assign trunc_ln2_fu_289_p4 = {{C_read_reg_368[31:2]}};

endmodule //tTest_Block_entry2347_proc6
