import numpy as np
import numpy.typing as npt

class Collector(object):
    def __init__(self, traceLength: int) -> None: ...
    def addTrace8(self, trace: npt.NDArray[np.uint8]) -> None: ...
    def addTrace10(self, trace: npt.NDArray[np.uint16]) -> None: ...
    def decimate(self) -> None: ...
    def getHistograms(self) -> npt.ArrayLike: ...
    pass
